'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,ChevronRight,Clock3,MapPin,Menu,Moon,Play,Sun,X} from 'lucide-react';
import gsap from 'gsap';
const issues=[['Pothole','In Progress','Road & Infrastructure'],['Street Light','Pending','Electricity'],['Water Leak','In Progress','Water'],['Garbage','Resolved','Sanitation']];
export default function Home(){
 const [dark,setDark]=useState(false); const [open,setOpen]=useState(false); const [submitted,setSubmitted]=useState(false); const [mobile,setMobile]=useState(false);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('civic-theme',dark?'dark':'light'); gsap.fromTo('.fade',{opacity:0,y:30},{opacity:1,y:0,duration:.9,stagger:.09,ease:'power3.out'}); gsap.to('.float',{y:-10,duration:2.5,repeat:-1,yoyo:true,ease:'sine.inOut'});},[dark]);
 return <main>
 <nav className="nav container"><a href="#top" style={{fontWeight:700,fontSize:20,letterSpacing:'-.04em'}}>CivicFlow<span style={{color:'var(--accent)'}}>.</span></a><div className="navlinks" style={{display:'flex',gap:28}}><a href="#how">How It Works</a><a href="#citizens">For Citizens</a><a href="#authorities">For Authorities</a><a href="#about">About</a></div><div style={{display:'flex',gap:8,alignItems:'center'}}><button className="btn btn-ghost" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={16}/>:<Moon size={16}/>}</button><button className="btn btn-primary" onClick={()=>setOpen(true)}>Report a Problem <ArrowRight size={15} style={{verticalAlign:'middle'}}/></button><button className="btn btn-ghost" onClick={()=>setMobile(!mobile)} style={{display:'none'}}><Menu size={18}/></button></div></nav>
 {mobile&&<div className="container card" style={{padding:20,marginTop:10}}><a href="#how">How It Works</a><br/><a href="#citizens">For Citizens</a></div>}
 <section id="top" className="section container" style={{paddingTop:70}}><div style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:54,alignItems:'center'}}><div><span className="pill fade">SMART CIVIC INFRASTRUCTURE</span><h1 className="hero-title serif fade" style={{margin:'25px 0'}}>Your city has problems.<br/><i style={{color:'var(--accent)'}}>Now there's a better way</i> to solve them.</h1><p className="fade" style={{fontSize:18,lineHeight:1.6,color:'var(--muted)',maxWidth:580}}>Report civic issues, track their progress, and make sure the right people are working to solve them.</p><div className="fade" style={{display:'flex',gap:10,marginTop:28}}><button className="btn btn-primary" onClick={()=>setOpen(true)}>Report a Problem <ArrowRight size={16}/></button><a className="btn btn-ghost" href="#how" style={{textDecoration:'none',color:'inherit'}}>See How It Works</a></div></div><div className="city fade grid-bg"><div className="building" style={{height:190,left:'17%',top:'26%'}}/><div className="building" style={{height:240,left:'38%',top:'15%',width:76}}/><div className="building" style={{height:155,left:'62%',top:'32%',width:58}}/><div className="road"/><div className="float" style={{position:'absolute',left:'47%',top:'43%',background:'#8d9b72',width:100,height:22,borderRadius:14}}/><div className="marker" style={{left:'8%',top:'14%'}}>● Pothole · In Progress</div><div className="marker" style={{right:'7%',top:'22%'}}>● Street Light · Pending</div><div className="marker" style={{left:'10%',bottom:'13%'}}>● Water Leak · In Progress</div><div className="marker" style={{right:'10%',bottom:'12%'}}>● Garbage · Resolved</div><button className="btn btn-primary" onClick={()=>setOpen(true)} style={{position:'absolute',left:'50%',top:'50%',transform:'translate(-50%,-50%)',width:62,height:62,padding:0,border:'4px solid #ffffff99'}}><Play size={21} fill="currentColor" style={{marginLeft:3}}/></button></div></div></section>
 <section className="container" style={{borderTop:'1px solid var(--border)',borderBottom:'1px solid var(--border)',display:'grid',gridTemplateColumns:'repeat(4,1fr)'}}>{[['Report','Submit civic issues in just a few taps.'],['Track','Track real-time progress.'],['Resolve','Authorities take action.'],['Verify','Citizens verify the resolution.']].map(([a,b],i)=><div className="stat fade" key={a}><small style={{color:'var(--accent)'}}>0{i+1}</small><h3 style={{margin:'12px 0 5px'}}>{a}</h3><p style={{color:'var(--muted)',fontSize:13,lineHeight:1.5}}>{b}</p></div>)}</section>
 <section id="how" className="section container"><div className="fade"><span className="pill">HOW IT WORKS</span><h2 className="serif" style={{fontSize:'clamp(2.5rem,5vw,5rem)',letterSpacing:'-.05em',margin:'18px 0 60px'}}>From street-level problem<br/>to verified resolution.</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:1,borderTop:'1px solid var(--border)'}}>{[['01','Report a Problem','Add description, location and evidence.'],['02','We Process It','System categorizes, prioritizes and routes it.'],['03','Action Is Taken','The correct verified authority receives it.'],['04','You Verify','Citizen confirms the issue is actually fixed.']].map(x=><div className="fade" style={{padding:'28px 20px 10px',borderBottom:'1px solid var(--border)'}} key={x[0]}><div className="mono" style={{color:'var(--accent)',fontSize:12}}>{x[0]}</div><h3>{x[1]}</h3><p style={{color:'var(--muted)',lineHeight:1.6}}>{x[2]}</p><ChevronRight size={18} color="var(--accent)"/></div>)}</div></section>
 <section id="citizens" className="section container" style={{paddingTop:40}}><div className="card" style={{padding:35,display:'grid',gridTemplateColumns:'1fr 1fr',gap:40}}><div><span className="pill">CITIZEN DASHBOARD</span><h2 className="serif" style={{fontSize:45,letterSpacing:'-.05em'}}>Know what happens<br/>after you report.</h2><p style={{color:'var(--muted)',lineHeight:1.7}}>Every complaint gets a traceable ID, department, verified authority, SLA and resolution timeline.</p><button className="btn btn-primary" onClick={()=>setOpen(true)}>Start a report <ArrowRight size={15}/></button></div><div style={{background:'var(--bg)',border:'1px solid var(--border)',padding:20,borderRadius:16}}><div className="mono" style={{fontSize:11,color:'var(--muted)'}}>CMP-2026-001245</div><h3>Pothole near Main Gate</h3><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><span className="pill">HIGH</span><span className="pill" style={{color:'var(--accent)'}}>IN PROGRESS</span></div><p style={{color:'var(--muted)',fontSize:13}}><MapPin size={13}/> Raj Nagar, Ghaziabad</p><div style={{marginTop:25,borderLeft:'2px solid var(--accent)',paddingLeft:18}}><b>Work started</b><p style={{fontSize:12,color:'var(--muted)'}}>25 Aug · 09:15 AM</p><b>21h 14m remaining</b></div></div></div></section>
 <section id="authorities" className="section container"><div className="fade" style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:28}}><div><span className="pill">LIVE EXAMPLE</span><h2 className="serif" style={{fontSize:45,margin:'14px 0'}}>A city that listens<br/>with a system behind it.</h2></div><span style={{color:'var(--muted)',fontSize:13}}>Demo data · CivicFlow</span></div><div className="card" style={{overflow:'hidden'}}>{issues.map((x,i)=><div key={x[0]} style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr auto',padding:'20px 24px',borderBottom:i<3?'1px solid var(--border)':'none',alignItems:'center'}}><div><div className="mono" style={{fontSize:10,color:'var(--muted)'}}>CMP-2026-00{i+12}</div><b>{x[0]}</b></div><span style={{color:'var(--muted)',fontSize:13}}>{x[2]}</span><span className="pill" style={{width:'fit-content',color:x[1]==='Resolved'?'var(--success)':'var(--accent)'}}>{x[1]}</span><Clock3 size={16} color="var(--muted)"/></div>)}</div></section>
 <footer id="about" className="container" style={{padding:'60px 0 35px',borderTop:'1px solid var(--border)',display:'flex',justifyContent:'space-between',color:'var(--muted)',fontSize:13}}><div><b style={{color:'var(--text)',fontSize:18}}>CivicFlow.</b><br/><span>Better cities, one problem at a time.</span></div><span>© 2026 CivicFlow · Demo platform</span></footer>
 {open&&<div style={{position:'fixed',inset:0,zIndex:50,background:'#171716aa',display:'grid',placeItems:'center',padding:20}}><div className="card" style={{width:'min(560px,100%)',padding:30,position:'relative'}}>{submitted?<div style={{padding:'35px 10px',textAlign:'center'}}><div style={{margin:'auto',width:52,height:52,borderRadius:'50%',background:'var(--soft)',display:'grid',placeItems:'center',color:'var(--accent)'}}><Check/></div><h2 className="serif" style={{fontSize:36}}>Report received.</h2><p style={{color:'var(--muted)'}}>Your demo complaint <span className="mono">CMP-2026-001298</span> is being analyzed and routed.</p><button className="btn btn-primary" onClick={()=>{setOpen(false);setSubmitted(false)}}>Done</button></div>:<><button onClick={()=>setOpen(false)} style={{position:'absolute',right:18,top:18,border:0,background:'transparent',color:'var(--muted)',cursor:'pointer'}}><X/></button><span className="pill">NEW COMPLAINT</span><h2 className="serif" style={{fontSize:38,margin:'16px 0'}}>What needs fixing?</h2><label style={{fontSize:13}}>Title<input placeholder="e.g. Large pothole near college gate" style={field}/></label><label style={{fontSize:13,display:'block',marginTop:15}}>Description<textarea placeholder="Tell us what is happening..." rows={4} style={{...field,resize:'vertical'}}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:15}}><label style={{fontSize:13}}>Category<select style={field}><option>Road & Infrastructure</option><option>Sanitation</option><option>Electricity</option><option>Water</option></select></label><label style={{fontSize:13}}>Location<input placeholder="Ghaziabad" style={field}/></label></div><button className="btn btn-primary" onClick={()=>setSubmitted(true)} style={{marginTop:22,width:'100%'}}>Submit Complaint <ArrowRight size={15}/></button></>}</div></div>}
 </main>
}
const field:React.CSSProperties={display:'block',width:'100%',marginTop:7,padding:'13px 14px',border:'1px solid var(--border)',borderRadius:10,background:'var(--bg)',color:'var(--text)',outline:'none'};
